### ISSUE TITLE
Error running on Android

### ISSUE THREAD

**Issue by kinhunt** [corymsmith/react-native-icons#110]
Hi:

I followed the Readme instructions and build passed. It gives me this error from logcat when running on device:

```
E/unknown:React( 1632): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `string'
E/unknown:React( 1632):     at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
E/unknown:React( 1632):     at com.facebook.react.uimanager.CatalystStylesDiffMap.getInt(CatalystStylesDiffMap.java:67)
E/unknown:React( 1632):     at com.facebook.react.views.text.ReactTextShadowNode.updateProperties(ReactTextShadowNode.java:313)
E/unknown:React( 1632):     at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:256)
E/unknown:React( 1632):     at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:React( 1632):     at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:React( 1632):     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
E/unknown:React( 1632):     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:126)
E/unknown:React( 1632):     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
E/unknown:React( 1632):     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:326)
E/unknown:React( 1632):     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React( 1632):     at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:React( 1632):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 1632):     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React( 1632):     at android.os.Looper.loop(Looper.java:136)
E/unknown:React( 1632):     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
E/unknown:React( 1632):     at java.lang.Thread.run(Thread.java:841)
```

**Comment by corymsmith** [comment]
@kinhunt What version of React Native are you using? And what version of this library?

I believe this is the same issue as https://github.com/facebook/react-native/issues/2855, https://github.com/facebook/react-native/issues/3216 and https://github.com/facebook/react-native/issues/2983

**Comment by kinhunt** [comment]
Hi @corymsmith 
RN: 0.11.4
RN-Icons: 0.5.0-rc

**Comment by corymsmith** [comment]
That version of React Native isn't compatible with 0.5.0-rc.

You'll have to upgrade your version of React Native or use 0.4.0 of this library

**Comment by kinhunt** [comment]
@corymsmith , thank you.
